console.log('# Load time');
console.time('micromatch');
exports.micro = require('micromatch');
console.timeEnd('micromatch');
console.time('minimatch');
exports.mini = require('minimatch');
console.timeEnd('minimatch');
console.time('picomatch');
exports.pico = require('..');
console.timeEnd('picomatch');
console.log();
