console.log('# Load time');
console.time('minimatch');
exports.mini = require('minimatch');
console.timeEnd('minimatch');
console.time('micromatch');
exports.micro = require('micromatch');
console.timeEnd('micromatch');
console.time('picomatch-lite');
exports.pico2 = require('..');
console.timeEnd('picomatch-lite');
console.time('picomatch-simple');
exports.pico = require('../../picomatch-simple/index.js');
console.timeEnd('picomatch-simple');
console.log();
