name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  FORCE_COLOR: 2

permissions: {}

jobs:
  run:
    name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16, 18, 20, 22, 24, 25]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: macos-latest
            node: 12
          - os: macos-latest
            node: 14

    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: ${{ matrix.node }}
          cache: npm
          cache-dependency-path: package.json

      - name: Update npm
        if: matrix.node == 12 || matrix.node == 14
        run: npm install -g npm@8

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      - name: Run Coveralls
        uses: coverallsapp/github-action@5cbfd81b66ca5d10c19b062c04de0199c215fb6e # v2
        if: startsWith(matrix.os, 'ubuntu') && matrix.node == 14
